controller:
  tag: "2.319.1"
  ingress:
    enabled: false
    apiVersion: networking.k8s.io/v1
    hostName: jenkins
  installPlugins:
  - kubernetes:1.31.2
  - workflow-aggregator:2.6
  - git:4.8.2
  - configuration-as-code:1.55.1
  - kubernetes-client-api::5.10.1-171.vaa0774fb8c20
 # - blueocean:1.25.0
